### ISSUE TITLE
Remove tooltips

### ISSUE THREAD

**Issue by T0RNATO** [Yirmiri/Yapping-Tooltips#3]
I can only imagine how long it took to write all those tooltips for every item in the game, so respect for that, but I'm making a modpack so I'd like to be able to only add tooltips to modded items and not have those since I assume people playing it know how the vanilla items work and they're a little bit in the way.

My request is this: either a config option to remove all of the default tooltips, or better, support for removing individual tooltips by doing something like this:
![image](https://github.com/user-attachments/assets/f864b9f0-627b-4221-9005-bd7816592fb8)

(Currently this just shows a blank newline)

The easiest fix would just be to add an empty string check at https://github.com/Yirmiri/Yapping-Tooltips/blob/f1a32314b7f93893bcd303d346c3a6b74be06b2f/src/main/java/net/azurune/yapping_tooltips/mixin/ItemStackMixin.java#L32

Thanks!

**Comment by T0RNATO** [comment]
(I also do think that a config file would be quite a lot more ergonomic to write descriptions than a lang file, and would also let you do more advanced things like adding tooltips to item tags, or removing specific tooltips, but it's probably a bit late for that now)

**Comment by Yirmiri** [comment]
I'll see what I can do for the next update, thanks for the feedback!

**Comment by Yirmiri** [comment]
I have made it so that tooltips that are empty will not be displayed. This feature will be available on v1.2 (which is uploading to CurseForge & Modrinth now)
